import type { ThemePreset } from './types'

export const STORAGE_KEY = 'garlic-claw:appearance'

export const DEFAULT_PRESET_ID = 'natural'

export const themePresets: ThemePreset[] = [
  {
    id: 'natural',
    name: '原色',
    hue: 200,
    saturation: 16,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: -14,
      accentSaturation: 48,
      accentLightness: 42,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 57,
      accentHueShift: -14,
      accentSaturation: 42,
      accentLightness: 62,
      brightness: 50,
    },
  },
  {
    id: 'orange',
    name: '橙',
    hue: 30,
    saturation: 22,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: 8,
      accentSaturation: 55,
      accentLightness: 44,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 57,
      accentHueShift: 8,
      accentSaturation: 48,
      accentLightness: 60,
      brightness: 50,
    },
  },
  {
    id: 'pink',
    name: '粉',
    hue: 340,
    saturation: 18,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: 5,
      accentSaturation: 52,
      accentLightness: 46,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 57,
      accentHueShift: 5,
      accentSaturation: 44,
      accentLightness: 62,
      brightness: 50,
    },
  },
  {
    id: 'blue',
    name: '蓝',
    hue: 220,
    saturation: 18,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: -8,
      accentSaturation: 50,
      accentLightness: 44,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 57,
      accentHueShift: -8,
      accentSaturation: 44,
      accentLightness: 62,
      brightness: 50,
    },
  },
  {
    id: 'green',
    name: '绿',
    hue: 150,
    saturation: 16,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: 8,
      accentSaturation: 45,
      accentLightness: 38,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 57,
      accentHueShift: 8,
      accentSaturation: 38,
      accentLightness: 56,
      brightness: 50,
    },
  },
  {
    id: 'purple',
    name: '紫',
    hue: 270,
    saturation: 20,
    light: {
      backgroundLightness: 97,
      foregroundLightness: 10,
      cardLightness: 100,
      borderLightness: 88,
      mutedForegroundLightness: 42,
      accentHueShift: 10,
      accentSaturation: 55,
      accentLightness: 48,
      brightness: 50,
    },
    dark: {
      backgroundLightness: 16,
      foregroundLightness: 88,
      cardLightness: 22,
      borderLightness: 28,
      mutedForegroundLightness: 58,
      accentHueShift: 10,
      accentSaturation: 48,
      accentLightness: 64,
      brightness: 50,
    },
  },
]

export const presetMap: Record<string, ThemePreset> = Object.fromEntries(
  themePresets.map((p) => [p.id, p]),
)

export function getPreset(id: string): ThemePreset {
  return presetMap[id] ?? presetMap[DEFAULT_PRESET_ID]
}
